[node]
rpc_bind = "127.0.0.1:20443"
p2p_bind = "127.0.0.1:20444"
bootstrap_node = "048dd4f26101715853533dee005f091632957e8ea8612482c6b9c3d5cbf7d489e0b5e4d22b82b2ca4e0e5d8c8b8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8"
working_dir = ".stacks-node/devnet"

[burnchain]
chain = "bitcoin"
mode = "xenon"
peer_host = "127.0.0.1"
username = ""
password = ""
rpc_port = 18443
peer_port = 18444

[connection_options]
read_only_call_limit_write_length = 0
read_only_call_limit_read_length = 100000
read_only_call_limit_write_count = 0
read_only_call_limit_read_count = 10000
read_only_call_limit_runtime = 1000000000

